# Generated by Django 3.1.10 on 2024-02-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20240210_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
