# Generated by Django 3.1.10 on 2024-02-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_profile_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
